### ISSUE TITLE
[WIP] Type annotation for the whole package

### ISSUE THREAD

**Issue by edwinb-ai** [DCI-NET/segmed#22]
This is a daunting task, even if the package is small. It is extensive, time-consuming and tedious. But is has the great advantage of standardization, robustness, flexibility and less error-prone source code, i.e., more like a true test-driven development style of code.

The following are options to achieve this:

- **Follow a standard:** For everything Python related, we use [Google's Python style guide](https://google.github.io/styleguide/pyguide.html#319-type-annotations)

- Use a type checker by default, some options are:
  - [`pyright`](https://github.com/Microsoft/pyright)
  - [`pytype`](https://github.com/google/pytype)
  - [`mypy`](http://www.mypy-lang.org/)

- Automate type checking and testing, some options for this are:
  - [`nox`](https://nox.thea.codes/en/stable/index.html)
  - [`Invoke`](https://www.pyinvoke.org/)

**Comment by edwinb-ai** [comment]
We should also look into `TensorFlow` specific types, as I'm aware that the actual `TensorFlow` source code is **not** type annotated, I don't know if actual types exist for this kind of objetcs.

Or is it that the actual object, such as `numpy.ndarray` are the types that we can use to annotate the code. @gmagannaDevelop

**Comment by gmagannaDevelop** [comment]
As you said previously, this task is extensive, time-consuming and tedious. 
Nevertheless I strongly agree on the benefits of typed Python code. 

I'll dive into the documentation to properly start type-annotating the package's scripts.

**Comment by edwinb-ai** [comment]
For an initial, automated type format we could use [MonkeyType](https://monkeytype.readthedocs.io/en/stable/) which automatically generates type stubs when code is executed. This could be helpful for the first time to avoid doing everything by hand, and then adjusting properly if the types are not correctly inferred (which _will_ be the case).

**Comment by edwinb-ai** [comment]
TensorFlow [has been working](https://github.com/tensorflow/tensorflow/issues/12345) on generating type stubs for most of the general and specific types used in the library, and there are other places we could look at if needed, like [`tensorflow-stubs`](https://github.com/persephone-tools/tensorflow-stubs).

**Comment by edwinb-ai** [comment]
In commit 43c7d9d I started looking into static type checking using `mypy`. It turns out that without [stub files](https://www.python.org/dev/peps/pep-0484/#stub-files) most of the imports are not recognized. With this, even though type annotation is useful, type checking which is the ultimate goal here is kind of useless.

There seems to be two options:

1. Create stub files for all the common types used in `segnet`.

2. Avoid using type checking, and with that rely on the developers experience to correctly type most of the code.

Can you have have a look at this @gmagannaDevelop ?

**Comment by edwinb-ai** [comment]
Closing in favor of the new 0.7 version where this is already implemented, see f639db82d77c52d93e639745c745af4cbaa866ce .
